apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9094
    uid: prometheus
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: "10s"

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5437
    uid: postgres
    database: ${DB_NAME}_${STUDENT_ID}
    user: ${DB_USER}
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: ${DB_PWD}